#!/bin/sh
#
# usage: gen_pixel_format.sh pixel_format_table.c

KDFS=${KDFS:-kdfs}

output_file="$1"

gen_table() {
	"$KDFS" compat --json --with 'PIXMAN_*' 'DRM_FORMAT_*' | jq -r '
		to_entries[]
		| select((.value | length) > 0)
		|
			"	{\n" +
			"		.drm_format = \(.key),\n" +
			(
				[.value | to_entries[] |
					"		.pixman_format = \(.key),\n"
				] | join("")
			) +
			"	},"
	'
}

cat >"$output_file" << EOF
// Generated by gen_pixel_formats.sh - DO NOT EDIT

#include <drm_fourcc.h>
#include "render/pixman.h"

const struct wlr_pixman_pixel_format formats[] = {
$(gen_table)
};

const size_t formats_len = sizeof(formats) / sizeof(formats[0]);
EOF
