// Generated by gen_pixel_formats.sh - DO NOT EDIT

#include <drm_fourcc.h>
#include "render/pixman.h"

const struct wlr_pixman_pixel_format formats[] = {
	{
		.drm_format = DRM_FORMAT_ABGR1555,
		.pixman_format = PIXMAN_a1b5g5r5,
	},
	{
		.drm_format = DRM_FORMAT_ABGR16161616,
		.pixman_format = PIXMAN_a16b16g16r16,
	},
	{
		.drm_format = DRM_FORMAT_ABGR2101010,
		.pixman_format = PIXMAN_a2b10g10r10,
	},
	{
		.drm_format = DRM_FORMAT_ABGR4444,
		.pixman_format = PIXMAN_a4b4g4r4,
	},
	{
		.drm_format = DRM_FORMAT_ABGR8888,
		.pixman_format = PIXMAN_a8b8g8r8,
		.pixman_format = PIXMAN_r8g8b8a8,
	},
	{
		.drm_format = DRM_FORMAT_ARGB1555,
		.pixman_format = PIXMAN_a1r5g5b5,
	},
	{
		.drm_format = DRM_FORMAT_ARGB2101010,
		.pixman_format = PIXMAN_a2r10g10b10,
	},
	{
		.drm_format = DRM_FORMAT_ARGB4444,
		.pixman_format = PIXMAN_a4r4g4b4,
	},
	{
		.drm_format = DRM_FORMAT_ARGB8888,
		.pixman_format = PIXMAN_a8r8g8b8,
		.pixman_format = PIXMAN_a8r8g8b8_sRGB,
		.pixman_format = PIXMAN_b8g8r8a8,
	},
	{
		.drm_format = DRM_FORMAT_BGR233,
		.pixman_format = PIXMAN_b2g3r3,
	},
	{
		.drm_format = DRM_FORMAT_BGR565,
		.pixman_format = PIXMAN_b5g6r5,
	},
	{
		.drm_format = DRM_FORMAT_BGR888,
		.pixman_format = PIXMAN_b8g8r8,
		.pixman_format = PIXMAN_r8g8b8,
		.pixman_format = PIXMAN_r8g8b8_sRGB,
	},
	{
		.drm_format = DRM_FORMAT_BGRA8888,
		.pixman_format = PIXMAN_a8r8g8b8,
		.pixman_format = PIXMAN_a8r8g8b8_sRGB,
		.pixman_format = PIXMAN_b8g8r8a8,
	},
	{
		.drm_format = DRM_FORMAT_BGRX8888,
		.pixman_format = PIXMAN_b8g8r8x8,
		.pixman_format = PIXMAN_x8r8g8b8,
	},
	{
		.drm_format = DRM_FORMAT_RGB332,
		.pixman_format = PIXMAN_r3g3b2,
	},
	{
		.drm_format = DRM_FORMAT_RGB565,
		.pixman_format = PIXMAN_r5g6b5,
	},
	{
		.drm_format = DRM_FORMAT_RGB888,
		.pixman_format = PIXMAN_b8g8r8,
		.pixman_format = PIXMAN_r8g8b8,
		.pixman_format = PIXMAN_r8g8b8_sRGB,
	},
	{
		.drm_format = DRM_FORMAT_RGBA8888,
		.pixman_format = PIXMAN_a8b8g8r8,
		.pixman_format = PIXMAN_r8g8b8a8,
	},
	{
		.drm_format = DRM_FORMAT_RGBX8888,
		.pixman_format = PIXMAN_r8g8b8x8,
		.pixman_format = PIXMAN_x8b8g8r8,
	},
	{
		.drm_format = DRM_FORMAT_XBGR1555,
		.pixman_format = PIXMAN_x1b5g5r5,
	},
	{
		.drm_format = DRM_FORMAT_XBGR2101010,
		.pixman_format = PIXMAN_x2b10g10r10,
	},
	{
		.drm_format = DRM_FORMAT_XBGR4444,
		.pixman_format = PIXMAN_x4b4g4r4,
	},
	{
		.drm_format = DRM_FORMAT_XBGR8888,
		.pixman_format = PIXMAN_r8g8b8x8,
		.pixman_format = PIXMAN_x8b8g8r8,
	},
	{
		.drm_format = DRM_FORMAT_XRGB1555,
		.pixman_format = PIXMAN_x1r5g5b5,
	},
	{
		.drm_format = DRM_FORMAT_XRGB2101010,
		.pixman_format = PIXMAN_x2r10g10b10,
	},
	{
		.drm_format = DRM_FORMAT_XRGB4444,
		.pixman_format = PIXMAN_x4r4g4b4,
	},
	{
		.drm_format = DRM_FORMAT_XRGB8888,
		.pixman_format = PIXMAN_b8g8r8x8,
		.pixman_format = PIXMAN_x8r8g8b8,
	},
};

const size_t formats_len = sizeof(formats) / sizeof(formats[0]);
